### ISSUE TITLE
error running tutoral

### ISSUE THREAD

**Issue by MattFenner** [Azure/vagrant-azure#116]
so i tried running the quick start on this page https://github.com/Azure/vagrant-azure

and it doesnt seem to work.

I get the following error:

```
PS C:\vagrantplay2> vagrant up --provider=azure
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Microsoft Azure Provider:
* The following settings shouldn't exist: client_id, client_secret, tenant_id
* vagrant_azure.subscription_id.required
* vagrant_azure.mgmt_certificate.required
* vagrant_azure.mgmt_endpoint.required
* vagrant_azure.vm_name.required
```

i feel like the documentation has been updated but the code version i installed doesnt match or something? Im new to vagrant so im not really sure if ive done something wrong

**Comment by devigned** [comment]
Based on the above output, I'm guessing you are running a plugin version less than 2.0 (currently preview). You can verify this via `vagrant plugin list` and note the version of vagrant-azure there.

If you'd like to see documentation for that version, please see the readme at the tagged version number. For example, v1.3 is tagged here: https://github.com/Azure/vagrant-azure/tree/v1.3.0. That should provide you with the documentation for that version.

Also, `vagrant plugin install -h` will show you information for installing a specific version of the plugin via `--plugin-version PLUGIN_VERSION`.

**Comment by MattFenner** [comment]
Yep i am running v1.3 thanks.

Maybe you was to make the front page more clear so you don't confuse others. since following the steps word for word installed v1.3 and therefore didnt work

**Comment by MattFenner** [comment]
Also can i ask how stable v2.0 is? the configuration seems nicer. are we expecting it to become the gold version soon or is it still a ways off? Im starting a new project and just wondering which version i should use.

**Comment by devigned** [comment]
@MattFenner thank you. Your right. That documentation would be helpful. We'll get it added to the readme.

I'm super excited about 2.0 as it finally moves us off of Azure Service Management and onto Azure Resource Manager. Currently, 2.0 doesn't support Windows VMs in Azure, but we are working on it. I don't think feature parity for 1.3 is very far off.

Basically, we scrapped everything but the skeleton of the 1.3 gem and performed a full house cleaning for 2.0. Now we are just adding back pieces where they make sense.

Using the new ARM SDK for Ruby (`azure_mgmt_*` gems) made this implementation much cleaner.

**Comment by rysweet** [comment]
Hi Matt,

I’ve been trying to give 2.0.0.pre1 a workout and submitted a minor pull request to add support for windows guests. I’ve tested on Windows 10 against ARM SDK 2.9 with Ubuntu and Windows 10 with ruby 2.2.3 and vagrant 1.8.1.

You can try it by removing the 1.3 version and then:

Ø  vagarant plugin install vagrant-azure --plugin-version 2.0.0.pre1

Which will get you the version that works for linux guests.  You can find the changes for windows guests under “pull requests”.  “vagrant powershell” and a few other things are still not wired up.

-Ryan

**Comment by christopher-hirudayasamy** [comment]
@devigned Is that possible to configure Windows VMs in Azure? I have installed **azure --plugin-version 2.0.0.pre1**. While running Vagrant up command i am facing below issue

> There are errors in the configuration of this machine. Please fix the following errors and try again:Microsoft Azure Provider:* The following settings shouldn't exist: vm_image

Could you help me on this?

**Comment by devigned** [comment]
in version 2.0.0.pre2 we reintroduced Windows support. Please give it a run.
