### ISSUE TITLE
Vagrant up fails on nokogiri module

### ISSUE THREAD

**Issue by avishnyakov** [Azure/vagrant-azure#124]
Got vagrant-azure plugin installed, all as per the guides. Running vagrant up on Win10 gives the following error.

Found also related (maybe) issue at Vagrant repo. Not sure what the resolution can be:
https://github.com/mitchellh/vagrant/issues/3769

Any ideas?

```
C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:29:in `rescue in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/nokogiri-1.6.3.1-x86-mingw32/lib/nokogiri.rb:25:in `<top (required)>'
        from C:/Users/antonv/.vagrant.d/gems/gems/azure-0.7.0/lib/azure.rb:17:in `require'
        from C:/Users/antonv/.vagrant.d/gems/gems/azure-0.7.0/lib/azure.rb:17:in `<top (required)>'
        from C:/Users/antonv/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/config.rb:7:in `require'
        from C:/Users/antonv/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/config.rb:7:in `<top (required)>'
        from C:/Users/antonv/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/plugin.rb:28:in `require_relative'
        from C:/Users/antonv/.vagrant.d/gems/gems/vagrant-azure-1.3.0/lib/vagrant-azure/plugin.rb:28:in `block in <class:Plugin>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/registry.rb:27:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/registry.rb:27:in `get'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:451:in `block in finalize!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:446:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/kernel_v2/config/vm.rb:446:in `finalize!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:50:in `block in finalize!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:49:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/root.rb:49:in `finalize!'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/v2/loader.rb:21:in `finalize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/config/loader.rb:168:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:740:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:486:in `host'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:208:in `block in action_runner'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:33:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:33:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:473:in `hook'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:722:in `unload'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:177:in `ensure in <main>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/bin/vagrant:177:in `<main>'
```

**Comment by avishnyakov** [comment]
Aha, see this one: nokogiri error #117
>> i think i might have fixed it by uninstalling vagrant 1.8.0 and going back to 1.7.3
>> im not getting a different error, but i think it is unrelated

Checking....

**Comment by avishnyakov** [comment]
Solved by getting Vagrant 1.7.3 installed.

**Comment by devigned** [comment]
In the 2.0 preview, there is no more dependency on nokogiri. Though, I think you have figured this out based on your other issue related to 2.0 preview.

**Comment by avishnyakov** [comment]
@devigned how do you think I figured out that 2.0 preview event exists at all? 

Spent a few hours with configuration, various setups I could think of, and then with ruby source code, double-checked github repo + saw the 2.0 branch, hm... So 2.0! Alright, met gems concepts (hello Ruby in 2 hours master class), tried to get the sources and make the bundle (compile the plugin locally so I can have the 2.0), then figured out how the plugins are distributed for vagrant and there is the public gems repo ( https://rubygems.org/gems/vagrant-azure/versions/1.3.0 ) and then finally saw (BINGO) 2.0.0.pre1 version, and then finally figured out the following update:
```
vagrant plugin install vagrant-azure --plugin-version '2.0.0.pre1' --plugin-prerelease
```

Was it fun? Absolutely!
Was it necessary? :) 

Sarcastically happy to do that on my own, of course, questioning if it is hard to put a few mentioning in the readme-whatever file on how to get started.  

Exploring vagrant-azure to see if we can get rid of our custom PS for Azure VM provision, moving fully to vagrant (for both Azure RM and Hyper-V scenarios). So far mixed impression, seems it needs more love and contributions to get some maturity. Anything I can help with?

**Comment by devigned** [comment]
I thought I had merged it already via: https://github.com/Azure/vagrant-azure/pull/114. Unfortunately, that must have gotten lost in the mix.

Agreed. You should not have had to go through that. Thank you for the gentle nudge to get it updated.

> Exploring vagrant-azure to see if we can get rid of our custom PS for Azure VM provision, moving fully to vagrant (for both Azure RM and Hyper-V scenarios). So far mixed impression, seems it needs more love and contributions to get some maturity. Anything I can help with?

:100:

If you are interested in taking a look where [this](https://github.com/Azure/vagrant-azure/pull/115) left off. That's the next item on the list. Adding back support (except now for ARM) for Windows VMs.

Besides that. If there is any other issue or areas you feel interested in, please open an issue / pr and I'll get it pulled in.

Thank you for the interest!
