### ISSUE TITLE
Unknown, unclear configiuration for Azure app  credentials

### ISSUE THREAD

**Issue by avishnyakov** [Azure/vagrant-azure#127]
Seems that be another read.me update :)

Configured all as per the readme, stumbled upon AZURE_CLIENT_ID / AZURE_CLIENT_SECRET setup. Got a new app in the Azure AD, seems to be fine. Run vagrant up, it failed with the following exception:

```
The client 'XXX' with object id 'YYY' does not have authorization to perform action 'Microsoft.Compute/locations/publishers/artifacttypes/offers/skus/versions/read' over scope '/subscriptions/XXX'.
```

Alright, seems the app does not have correct permissions. So..
- What are the permissions required and how to setup them correctly?
- How to create a new app correctly?

Frankly saying, it is getting a bit messy and I am more than happy to contribute for end-to-end manual on how to get vagrant-azure up and running. Already spent some time hitting random issues, troubleshooting and guessing around, wonder how I can help to improve that.

**Comment by devigned** [comment]
I'd give subscription contributor access. That way you will have the ability to create new resource groups, and create / read resources across resource providers.

**Comment by avishnyakov** [comment]
Sure thing, how to do that?

**Comment by kpfaulkner** [comment]
Any luck with this? Just hitting this myself. Have been "playing around" in Azure AD trying to figure out what permission I'm missing, but no luck so far. :(

**Comment by avishnyakov** [comment]
Hey mate, I switched to Terraform, but it has the following Azure RM setup manual:
https://www.terraform.io/docs/providers/azurerm/

Check out "Creating Credentials" section, the most important is "To enable the application for use with Azure RM, you now need to switch to the 'New' Portal:" and further. You need to add that app credential to the Azure portal and give permission. Trick is about adding by name manually as "Type in the name of the application added in the 'Classic' Portal. You need to type this as it won't be shown in the user list. Click on the appropriate user in the list and then click Select"

Once all done, Terraform works well with AZURE_CLIENT_ID / AZURE_CLIENT_SECRET and the rest of the things and so must Vagrant.

Give it a go, I believe that would be it.

**Comment by kpfaulkner** [comment]
Brilliant!  I was doing the same as that but the user I added was at resource group level and not subscription. Once I moved to subscription all was good!

Thanks heaps!

**Comment by MattFenner** [comment]
@avishnyakov keep in mind the azure rm plugin to terraform is pretty new. if you don't care too much you may want to use the azure classic provider since it is more stable.

I tried using the RM one and ended up giving up and switching to the classic (SM) one. Allthough they seem to have made a lot of improvements lately so it might be better now.

**Comment by avishnyakov** [comment]
Thanks. Evaluating, don't see deal breakers to go back to the classic one.

What were the challenges in your case? Bootstrapping VMs only has a limited scope, say networking / storage accounts / affinity groups and pretty mush that's it. All that works well so farm for RM.

**Comment by kpfaulkner** [comment]
I'm still using the vagrant + plugin for now. I'm new the vagrant...   still taking small steps. Thanks again for the help!

**Comment by MattFenner** [comment]
@avishnyakov in my case i was getting a lot of random errors, and the error reporting was extremely basic (i.e. it basically just said an error occurred and no details of what the error was).

Like i said i think they have fixed a lot of this in the past week or so though.

**Comment by devigned** [comment]
Check out this article on assigning roles to accounts (including service principals) https://azure.microsoft.com/en-us/documentation/articles/role-based-access-control-configure/. 

You will need to have contributor access to the subscription for the service principal account.

@avishnyakov please let me know if that solves your issue.

**Comment by devigned** [comment]
I'd recommend using the Azure CLI to setup the service principles and the correct role for the service principle in Azure Resource Manager. See https://docs.microsoft.com/en-us/cli/azure/install-az-cli2.

You'd use the following command:
```
$ az ad sp create-for-rbac -h

Command
    az ad sp create-for-rbac: Create a service principal and configure its access to Azure
    resources.

Arguments
    --expanded-view: Once created, display more information like subscription and cloud
                     environments.
    --name -n      : A display name or an app id uri. Command will generate one if missing.
    --password     : The password used to login. If missing, command will generate one.
    --role         : Role the service principal has on the resources.  Default: Contributor.
    --scopes       : Space separated scopes the service principal's role assignment applies to.
                     Defaults to the root of the current subscription.
    --years        : Years the password will be valid.  Default: 1.

Global Arguments
    --debug        : Increase logging verbosity to show all debug logs.
    --help -h      : Show this help message and exit.
    --output -o    : Output format.  Allowed values: json, jsonc, list, table, tsv.  Default: json.
    --query        : JMESPath query string. See http://jmespath.org/ for more information and
                     examples.
    --verbose      : Increase logging verbosity. Use --debug for full debug logs.

Examples
    Create with defaults
        az ad sp create-for-rbac
    Create with a custom name
        az ad sp create-for-rbac -n "http://my-app"
    Create role assignments at the same time
        az ad sp create-for-rbac -n "http://my-app" --role contributor --scopes
        /subscriptions/11111111-2222-3333-4444-555555555555/resourceGroups/mygroup
        /subscriptions/11111111-2222-3333-4444-666666666666/resourceGroups/my-another-group
    Login with this service principal
        az login --service-principal -u <name> -p <password> --tenant <tenant>
    Reset credentials on expiration
        az ad sp reset-credentials --name <name>
    Create role assignments
        az role assignment create --assignee <name> --role Contributor
    Revoke the service principal when done with it
        az ad app delete --id <name>
```

**Comment by servercharlie** [comment]
# Spin up dockerized azure cli

```
docker run -v ${HOME}:/root -it azuresdk/azure-cli-python:latest
# https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
```

# Navigate to the "To create using Azure CLI" section on this page below.

https://www.terraform.io/docs/providers/azurerm/

# You'll get the following:

```
{
  "appId": "05da42bd-6db2-44f0-bd8f-XXXXXXXXXXXX", --> CLIENT ID
  "displayName": "azure-cli-2017-XX-XX-XX-XX-XX",
  "name": "http://azure-cli-2017-XX-XX-XX-XX-XX",
  "password": "f5cf473b-1564-46e4-9e3c-XXXXXXXXXXXX", --> CLIENT SECRET
  "tenant": "72798e6e-1ac8-4c0b-8795-XXXXXXXXXXX" --> TENANT ID
}
```

**Comment by rtargosz** [comment]
We recently had this issue with the same message and found that it was caused by the user being logged in with a different subscription (we have 2). Using az login --subscription <id> resolved the problem for us.
