### ISSUE TITLE
Provide option for UDP port forwarding

### ISSUE THREAD

**Issue by kkorsakov** [Azure/vagrant-azure#23]
Now only TCP endpoints can be provisioned. Please add option for UDP port provisioning also

**Comment by pawelsawicz** [comment]
Hey, I am working on this https://github.com/pawelsawicz/vagrant-dontstarve project and it require to set up UDP ports if you want I can handle with this issue.

**Comment by devigned** [comment]
As of v2.0.0.pre8 `azure.tcp_endpoints` provision allowing both UDP and TCP.
