### ISSUE TITLE
Provide option for setting static ip

### ISSUE THREAD

**Issue by phstudy** [Azure/vagrant-azure#71]
Azure allows to set static ip when creating a VM.

The option in azure-cli, 
`$ azure vm create --help`
help:    Create a VM
help:    Usage: vm create [options] <dns-name> <image> [userName] [password]
help:    Options:
// omit
help:      -S, --static-ip <ip-address>           the static IP address assigned to the virtual machine
// omit

**Comment by avishnyakov** [comment]
Extremely keen to see static IP implemented as well.

**Comment by devigned** [comment]
In 2.0 preview, each vm gets a fully qualified domain name. Would that be sufficient to cover the desire for static IPs? If not, please explain the use case a bit more.

**Comment by avishnyakov** [comment]
In Azure there is a limit for FQDN (which some with public IP), the limit is 60 public IP and so the FQDN. Correct me if I am wrong here.

So hitting VMs with FQDN can fastly reach the limit 60 VMs per subscription (next you would ask the Azure Support yo increase that limit).

Next, not all VMs should be available via FQDN at all. In SharePoint typologies, say SQL, DC, Application Servers should not have these at all. WFEs as well, they should be exposed via Azure Public Load Balancer. So we go all with static IP all the time. Again, correct me if I am wrong.

Then various CI/CD scenarios + DSC based stuff. Nothing gets exposed publicly getting all the things from the within the current network, build controllers and DSC server. 

I might be completely wrong here, keen to see a better solution if any,

**Comment by devigned** [comment]
I think this get's to a bigger issue. Do you plan on spinning up and describing these complex structures in Vagrant-Azure? 

At this point, the gem is spinning up infrastructure based on a template (see: https://github.com/Azure/vagrant-azure/blob/v2.0/templates/arm/deployment.json.erb). Could it be modified to programmatically build out the template to create this complex infrastructure, absolutely. I wonder if that's the problem Vagrant was intended to solve.

I'm all for machines behind load balancers. That's a feature I definitely want to add in the near future. Though, I feel like I need to be able to SSH to those machines even if they are in the load balancer b/c I will need to provision some configuration for those machines post creation of the infrastructure. For the load balancer, I view that as more of a decoration over the basic provisioning connection.

**Comment by devigned** [comment]
Per the FQDN limit, I'll need to look into that.

**Comment by avishnyakov** [comment]
Not really.

Looking in vagrant-azure to only get VM provisioned in Azure from the image. The rest is done with DSC (or other configuration management tool). That's it. 

The thing with the static ip is that if it cannot be put into initial vagrant provision, then where would we put it at all and at which stage. The whole workflow of bootstrapping VM and passing to the CM tool seems to be incomplete as the IP is not set. As this is an Azure specific thing, we can't really fit it into CM tool, hence I am exploring if the vagrant boostrapping step is the right fit. And it seem that it is.

Any better solution on that?
