### ISSUE TITLE
Compatibility with Azure Pack?

### ISSUE THREAD

**Issue by halfsour** [Azure/vagrant-azure#73]
We are experimenting with MS Azure Pack as I was wondering if this would work with an Azure-Pack fronted SCVMM/Hyper-V private cloud as well if the "azure.mgmt_endpoint" is changed to our internal AzurePack URL listening on its default port?

**Comment by devigned** [comment]
It should just work as long as the version of azure pack supports the api_versions requested by the HTTP requests. Please update the thread with your experience. I know this is going to come up more as we embrace Azure Stack (new azure pack).

**Comment by halfsour** [comment]
I'm not sure how to validate the ap_versions.  The specific error looks like an unhanded 302 returned to the vagrant-azure plugin coming from the Azure Pack server.  Please let me know if there is specific info on the version of the Azure Pack server that I should ask the Windows team here to help.  Here is the stack trace:

$ vagrant status
==> default: Attempting to read state for vgrnt-umlq0 in vgrnt-umlq0-service-lkfuv
http error: 302/export/home/umlq/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/core/utility.rb:108:in `exception_message': http error: 302 (RuntimeError)
        from /export/home/umlq/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/management_http_request.rb:83:in `wait_for_completion'
        from /export/home/umlq/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/base_management/management_http_request.rb:55:in `call'
        from /export/home/umlq/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:39:in `block in list_virtual_machines'
        from /export/home/umlq/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:35:in `each'
        from /export/home/umlq/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:35:in `list_virtual_machines'
        from /export/home/umlq/.vagrant.d/gems/gems/azure-0.6.4/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:54:in `get_virtual_machine'
        from /opt/vagrant/vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/vagrant_azure_service.rb:26:in `get_virtual_machine'
        from /export/home/umlq/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/read_state.rb:30:in `read_state'
        from /export/home/umlq/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/read_state.rb:18:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
        from /export/home/umlq/.vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/action/connect_azure.rb:44:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:212:in `action_raw'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:189:in `block in action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:516:in `lock'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:176:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:176:in `action'
        from /opt/vagrant/vagrant.d/gems/gems/vagrant-azure-1.1.1/lib/vagrant-azure/provider.rb:58:in `state'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:478:in `state'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/machine.rb:141:in `initialize'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/vagrantfile.rb:75:in `new'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/vagrantfile.rb:75:in `machine'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:614:in `machine'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:201:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:201:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:200:in `map'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/plugin/v2/command.rb:200:in `with_target_vms'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/plugins/commands/status/command.rb:20:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.0/lib/vagrant/environment.rb:301:in `cli'
        from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.0/bin/vagrant:174:in `<main>'

**Comment by devigned** [comment]
ping back with your vagrantfile please

**Comment by SimSimY** [comment]
I have the same issue (with azure-0.6.X, the latest version comes with 0.7.0 which is broken as well) 
It is cauesed by redirect to ADFS:
in: lib\azure\base_management\management_http_request.rb
line: ~108
add:
  puts response.headers['location']
output:
https://SOME_DC/adfs/ls/?wa=wsignin1.0&wtrealm=http%3a%2f%2fazureservices%2fTenantSite&wctx=rm%3d0%26id%3dpassive%26ru%3d%2XXXX59faf77-XXXX-XXXX-XXXX-76f88e4d7152%252fservices%252fhosteds
ervices%26cx%3d0&wct=2015-08-30T13%3a13%3a59Z

**Comment by SimSimY** [comment]
Just to confirm - The plugin doesn't work with WAP, Even after setting the right port it fails when trying to query "services/images":



````
C:\temp\azure>vagrant up
==> default: Attempting to read state for test1 in test1-service-eqyca
C:/Users/simsimy/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/base_management/management_http_request.rb:19: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
Bringing machine 'default' up with 'azure' provider...
==> default: Attempting to read state for test1 in test1-service-aildd
==> default: Determining OS Type By Image
http error: 403
C:/Users/simsimy/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/core/utility.rb:152:in `exception_message': ?[31m?[1mhttp error: 403?[0m?[0m (RuntimeError)
        from C:/Users/simsimy/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/base_management/management_http_request.rb:90:in `wait_for_completion'
        from C:/Users/simsimy/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/base_management/management_http_request.rb:58:in `call'
        from C:/Users/simsimy/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/virtual_machine_image_management/virtual_machine_image_management_service.rb:36:in `list_os_images'
        from C:/Users/simsimy/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/virtual_machine_image_management/virtual_machine_image_management_service.rb:25:in `list_virtual_machine_images'
        from C:/Users/simsimy/.vagrant.d/gems/gems/azure-0.7.0/lib/azure/virtual_machine_management/virtual_machine_management_service.rb:468:in `get_image'
        from C:/Users/simsimy/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/vagrant_azure_service.rb:38:in `method_missing'
        from C:/Users/simsimy/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/os_type.rb:21:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/simsimy/.vagrant.d/gems/gems/vagrant-azure-1.2.1/lib/vagrant-azure/action/connect_azure.rb:44:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
`````


Vagrant file:
`````````ruby
Vagrant.configure('2') do |config|
    config.vm.box = 'azure'

    config.vm.provider :azure do |azure, override|
        azure.mgmt_certificate = 'simsimy.pem'
        azure.mgmt_endpoint = 'https://our.wap.domain:30006/'
        azure.subscription_id = '0X0X0X0X-0X0X-0X0X-0X0X-0X0X0X0X0X0X'
        azure.vm_name = 'test1' # max 15 characters. contains letters, number and hyphens. can start with letters and can end with letters and numbers
        azure.vm_password = 'some-pass' # min 8 characters. should contain a lower case letter, an uppercase letter, a number and a special character
        azure.vm_password = 'some-pass' # min 8 characters. should contain a lower case letter, an uppercase letter, a number and a special character    
        azure.winrm_transport = [ 'http', 'https' ] # this will open up winrm ports on both http (5985) and http (5986) ports
        azure.tcp_endpoints = '3389:53389' # opens the Remote Desktop internal port that listens on public port 53389. Without this, you cannot RDP to a Windows VM.
    end
end
``````

**Comment by devigned** [comment]
We'll work with the Azure Stack team to get to the bottom of this. Thank you for the great repro, @SimSimY.

**Comment by SimSimY** [comment]
Hi! are there any updates regarding this?

**Comment by PrahlM93** [comment]
@devigned, @SimSimY, any news on if this works with Windows Azure Pack?

**Comment by devigned** [comment]
We are not testing against Azure Pack, but we will support Azure stack.
