### ISSUE TITLE
Passing parameters into "vagrant powershell"?

### ISSUE THREAD

**Issue by RPrimrose** [Azure/vagrant-azure#79]
Is it possible to pass parameters into a script when running it via the "vagrant powershell" command? I can't find anything documented for this.

It's obviously possible to specify arguments to a script in your Vagrantfile when initially provisioning the VM, it'd be very handy for "vagrant powershell" to support the same thing.

**Comment by devigned** [comment]
That's a pretty cool idea. If you have a bit of time, that's a great candidate for a pr.

**Comment by codestothestars** [comment]
Looks like this was added to Vagrant itself?

https://www.vagrantup.com/docs/cli/powershell.html#_c_COMMAND

I would've thought this within that scope anyway.

**Comment by devigned** [comment]
At this point, the feature should be directed upstream to Vagrant. I'm going to close this issue.
