### ISSUE TITLE
Different behaviour when running a Powershell script via provisioning and when running via "vagrant powershell"

### ISSUE THREAD

**Issue by RPrimrose** [Azure/vagrant-azure#80]
I've a Powershell script that's intended to install the Microsoft Web Platform Installer onto a VM:

```
Invoke-Webrequest -uri "http://download.microsoft.com/download/7/0/4/704CEB4C-9F42-4962-A2B0-5C84B0682C7A/WebPlatformInstaller_amd64_en-US.msi" -outfile "c:\users\vagrant\downloads\wpi.msi"
msiexec -i c:\users\vagrant\downloads\wpi.msi /passive
```

If I run this by including `config.vm.provision "shell", path: "VagrantScripts/install-wpi.ps1"` in my Vagrantfile then it doesn't appear to work as nothing is created under C:\Program Files\Microsoft\Web Platform Installer and `webpicmd` is not recognised as a command by subsequent Powershell scripts.

However, if I provision the VM using the same Vagrantfile but then run the same script via `vagrant powershell -s VagrantScripts/install-wpi.ps1` it works fine. The expected installation directory is created and subsequent scripts have access to `webpicmd`.

Is it intended that Powershell scripts behave differently when run as part of provisioning? If so, would it be possible to include details of these differences in the documentation and possible workarounds?

My Vagrantfile is at https://gist.github.com/RPrimrose/df7ed03670da4ca9bba9 . Let me know if there are any logs etc that you need.

**Comment by devigned** [comment]
hmm... perhaps one is being run with elevated privileges. Try running it with --debug and keep an eye on the provisioning portion of the output (watch out, it is loud).

**Comment by devigned** [comment]
updated to the latest winrm gem. The bits are in master, give it a shot and ping back.
