### ISSUE TITLE
Enable adding data disks

### ISSUE THREAD

**Issue by ghost** [Azure/vagrant-azure#81]
From https://github.com/Azure/azure-sdk-for-ruby/blob/master/lib/azure/virtual_machine_management/virtual_machine_management_service.rb#L441 there's a function to add a data disk to a VM. Could this functionality be added to vagrant-azure?

**Comment by devigned** [comment]
That would be great functionality to add. Would you like to submit a pr?

**Comment by grhoff** [comment]
If time permits, I will do so.

Thanks.

Greg Hoffer
v-grhoff@microsoft.com

**Comment by grhoff** [comment]
I will when I get a chance.

**Comment by avishnyakov** [comment]
Should it even be within the Vagrant core functionality? 
Seems to be external feature, done after VM creation via DSC / custom PS or something like that.

**Comment by MattFenner** [comment]
people wanting more advanced stuff like this may want to check out terraform (at least in the mean time until this is implemented)

terraform supports more advanced configurations.

**Comment by avishnyakov** [comment]
That's the point. Basic creation of the VMs it is not same as VM configuration. Creation and configuration are two different things which should not be mixed together.

**Comment by 4c74356b41** [comment]
how are data disks configuration???

**Comment by devigned** [comment]
The first version of data disks has landed in v2.0.0.pre8. See: https://github.com/Azure/vagrant-azure/pull/190. 

Right now it adds empty disks, but will be updated to mount and attach existing disks.

Closing this issue. As we want new feature aligned to data disks, please add an issue.
