### ISSUE TITLE
Vagrant powershell re-executes after timeout

### ISSUE THREAD

**Issue by jdimmerman** [Azure/vagrant-azure#83]
If your vagrant powershell script/command runs for over some defined amount of time, looks like ~70 seconds, vagrant will call the same powershell script or command again.  The first process won't be killed.  If that second process goes over the allotted time, a third process will be created, etc.  You get into an infinite loop.

Each process will quit as execution finishes.

I'm still learning Ruby but will try to narrow this one down myself. 

To replicate with an environment already provisioned, with some vagrant vm name 'client1', call the following and watch the processes spawn on the vm guest OS.

vagrant.exe powershell client1 -c "Start-Sleep -s 120"

**Comment by devigned** [comment]
I think this will respect boot timeout, which I believe is set to 60 seconds by default.

```ruby
Vagrant.configure('2') do |config|
  config.vm.boot_timeout = 1000
```

Does this extend the timeout for you? If so, ps timeout really should be differentiated from boot timeout. Furthermore, the timeout should be caught and handled correctly (not retry).

**Comment by jdimmerman** [comment]
Unfortunately it is not the boot_timeout, though finding a way to extend this timeout in the meantime would be awesome.  The first powershell process does seem to be alive for roughly 70 seconds rather than 60 before the next one appears, but the extra 10 seconds might be the time it takes for vagrant to check the state of the machine and invoke the next process over winrm.

**Comment by jdimmerman** [comment]
This is actually the way vagrant handles the winrm timeout on the vm.  A temporary workaround is to extend the timeout so that you don't encounter it.  On the remote vm, run: 
     winrm set winrm/config '@{MaxTimeoutms="#######"}'  (I used 7200000)
Note that the single quotes around the @{} are only required in powershell, not if this is called from batch.

There are two issues with how vagrant azure handles the winrm timeouts, both regarding a script or command called from vagrant powershell
1) If a single powershell command that is invoking a second process on the vm (such as start-process with -wait) is responsible for the timeout, then the command will complete correctly on the remote vm, but control will never return to vagrant.  The user must kill two instances of ruby.exe on the vagrant host machine manually.  All processes quit correctly on the vm.
2) If multiple the powershell commands exceed the timeout limit themselves (without launching another process) then the entire script/command will be re-executed endlessly by vagrant.

**Comment by devigned** [comment]
Updated to the latest winrm gem. Please give it another shot and ping back. The gem is not released but the latest bits are in master.
