### ISSUE TITLE
Use automation account for authentication

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/vagrant-azure#94]
Hi,

is it possible to use an "automation account" for authentication against Azure instead of the publishsettingsfile or a cert with the Azure Vagrant Provider?

https://github.com/Azure/vagrant-azure/blob/master/lib/vagrant-azure/action/connect_azure.rb

Not a ruby specialist, but happy to tinker around with this file and make it work, unless someone else can do it faster or has already done it.

Cheers
David

**Comment by devigned** [comment]
Uhm... I'm not sure what is meant by an automation account. Please expand on this a bit.

Right now, the library targets Azure Service Management APIs and as such has only implemented cert based authentication. After the release of the Azure Resource Management libraries in Ruby, we'll update the library to use Azure Active Directory authentication.

**Comment by davidobrien1985** [comment]
The ruby gems are here as preview: https://rubygems.org/search?query=azure_mgmt

Yes, that's what I mean, using Azure AD for authentication. Sorry, "automation account" is just my habit of calling it.

Cheers
David

From:  David Justice
Reply-To:  Azure/vagrant-azure
Date:  Saturday, 29 August 2015 1:02 am
To:  Azure/vagrant-azure
Cc:  David O'Brien
Subject:  Re: [vagrant-azure] Use automation account for authentication (#94)


Uhm... I'm not sure what is meant by an automation account. Please expand on this a bit.

Right now, the library targets Azure Service Management APIs and as such has only implemented cert based authentication. After the release of the Azure Resource Management libraries in Ruby, we'll update the library to use Azure Active Directory authentication.

**Comment by devigned** [comment]
Yep, we just published the gems. 

Now the fun part of ripping the insides of this gem apart!
