### ISSUE TITLE
Use Azure Resource Manager instead of Service Management API

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/vagrant-azure#95]
Hi,

the Azure Provider should use the Azure Resource Manager instead of the Service Management API or at least give the user the option which API to use.

Default should be ARM, especially because ARM can deploy in parallel into a Resource Group, where SM deploys sequential.

Cheers
David

**Comment by devigned** [comment]
Yep. That is the plan right after the Ruby ARM libs are published.

**Comment by davidobrien1985** [comment]
Hi,

They are already here as preview: https://rubygems.org/search?query=azure_mgmt


From:  David Justice
Reply-To:  Azure/vagrant-azure
Date:  Saturday, 29 August 2015 1:03 am
To:  Azure/vagrant-azure
Cc:  David O'Brien
Subject:  Re: [vagrant-azure] Use Azure Resource Manager instead of Service Management API (#95)


Yep. That is the plan right after the Ruby ARM libs are published.

**Comment by solstikk** [comment]
Any progress on this? It would be very convenient!

**Comment by howie** [comment]
Yes, we also need it !:D

**Comment by vniklas** [comment]
Any news ?

**Comment by devigned** [comment]
There is a working prototype of Azure Resource Manager based Vagrant-Azure in the v2.0 branch. Please pull the code and give it a run. We'll publish out a preview gem shortly.

**Comment by avishnyakov** [comment]
+1 for this ine

**Comment by devigned** [comment]
Check out https://github.com/Azure/vagrant-azure#usage for the Azure Resource Manager preview.

**Comment by avishnyakov** [comment]
Thanks! 

Figured it out with 2.0 version, However having the following impediment:
* Unknown, unclear configiuration for Azure app credentials #127

**Comment by devigned** [comment]
Closing as v2.0 preview is out with ARM support
