### ISSUE TITLE
Error with Rubyzip rename for copying vagrant folder files

### ISSUE THREAD

**Issue by iaingblack** [Azure/vagrant-azure#96]
Getting this error creating a very general Windows Azure machine. It seems when it tries to zip the data in the VagrantFile folder and upload, it cannot rename the zip and crashes. Any ideas anyone? Using Vagrant 1.7.4 and Vagrant-Azure 1.2.1. I tried with Vagrant 1.7.2 and Vagrant-Azure 1.1.0 and it worked again (my previous working setup). I then upgraded vagrant-azure 1.1.0 to 1.2.1 and it failed again (though probably a dependency on latest Vagrant so unrelated?).
## Vagrant 1.7.4 and Vagrant-Azure 1.2.1 Error

==> default: Copying folder: C:/Provisioning/vagrant/octopus-tentacle ==>
==> default: /vagrant
==> default: Looking for WinRM
==> default: Found public port 5986
C:/HashiCorp/Vagrant/embedded/gems/gems/rubyzip-1.1.7/lib/zip/file.rb:416:in `re
name': Permission denied - (C:/Users/vagrant/AppData/Local/Temp/1/winrm_upload20
150902-2568-1cc7e5q.zip20150902-2568-nbsd8q, C:/Users/vagrant/AppData/Local/Temp
/1/winrm_upload20150902-2568-1cc7e5q.zip) (Errno::EACCES)
## Vagrant 1.7.2 and Vagrant-Azure 1.2.1 Error

==> default: VM Status: ReadyRole
==> default: Determining OS Type By Image
==> default: OS Type is Windows
    default: Looking for WinRM
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/conf
ig.rb:73:in `method_missing': undefined method`ssl_peer_verification=' for #<Va
grantPlugins::CommunicatorWinRM::Config:0x45b5020> (NoMethodError)

**Comment by JBuchter** [comment]
Having the same issue with Vagrant 1.7.2 and vagrant-azure 1.3.0

default: Looking for WinRM
default: Found public port 5986
C:/HashiCorp/Vagrant/embedded/gems/gems/rubyzip-1.1.7/lib/zip/file.rb:416:in `rename': Permission denied - (C:/Users/user/AppData/Local/Temp/winrm_upload20151008-4808-1wkof16.zip20151008-4808-546f9r, C:/Users/user/AppData/Local/Temp/winrm_upload20151008-4808-1wkof16.zip) (Errno::EACCES)

**Comment by ptrstpp950** [comment]
Same with Vagrtant 1.7.4 and vagrant-azure 1.3.0

**Comment by ptrstpp950** [comment]
The problem is old dependency to winrm-fs. Actually downloaded vesion is 0.2.0. There is a fix in 0.2.2 for this problem: https://github.com/WinRb/winrm-fs/commit/e93b67306c14b55a42f740e3ea159741ecfacec1

But I don't know (yet) how to fix above plugin to use at least 0.2.2 version
