### ISSUE TITLE
Possibility to create several instances under the same cloud service.

### ISSUE THREAD

**Issue by lionelperrin** [Azure/vagrant-azure#97]
I may have missed something, but it looks to me that it is not possible to create several VM instances using the same cloud service name.
Doing so, I get the following error message: 
`ConflictError : The specified deployment slot Production is occupied`

Reading the Azure SDK documentation, it looks that one should use add_role for the subsequent vm creations.

Is it already supported by Vagrant ? Could we add support for it ?

Regards,

**Comment by lionelperrin** [comment]
This issue looks closely related to the issue #76.

**Comment by kfm82** [comment]
I / we are still having this issue here, so we remain highly interested in any attempts at a solution.

**Comment by devigned** [comment]
Closing as the gem is now focused on Azure resource manager.
